export { default as SvgIconWrapper } from './wrapper/SvgIconWrapper';
export { default as SvgIcon } from './base/SvgIcon';

/*-- EXPORT ICON COMPONENTS --*/
export { default as PasswordsIcon } from './icons/PasswordsIcon';
export { default as PasswordHistoryIcon } from './icons/PasswordHistoryIcon';
export { default as SecurityDashboardIcon } from './icons/SecurityDashboardIcon';
export { default as PasswordChangerIcon } from './icons/PasswordChangerIcon';
export { default as LogOutIcon } from './icons/LogOutIcon';
export { default as ComputerIcon } from './icons/ComputerIcon';
export { default as ToolsIcon } from './icons/ToolsIcon';
export { default as RefreshIcon } from './icons/RefreshIcon';
export { default as WarningIcon } from './icons/WarningIcon';
export { default as ArrowDownIcon } from './icons/ArrowDownIcon';
export { default as CloseIcon } from './icons/CloseIcon';
export { default as SearchIcon } from './icons/SearchIcon';
export { default as DotsIcon } from './icons/DotsIcon';
export { default as GeneratorIcon } from './icons/GeneratorIcon';
export { default as WebIcon } from './icons/WebIcon';
export { default as VaultIcon } from './icons/VaultIcon';
export { default as CheckIcon } from './icons/CheckIcon';
export { default as CaretDownIcon } from './icons/CaretDownIcon';
export { default as LoaderIcon } from './icons/LoaderIcon';
export { default as SharedIcon } from './icons/SharedIcon';
export { default as NoNetworkIcon } from './icons/NoNetworkIcon';
export { default as HideIcon } from './icons/HideIcon';
export { default as RevealIcon } from './icons/RevealIcon';
export { default as CopyPasswordIcon } from './icons/CopyPasswordIcon';
export { default as EditIcon } from './icons/EditIcon';
