export { default as SvgIconWrapper } from './wrapper/SvgIconWrapper';
export { default as SvgIcon } from './base/SvgIcon';

/*-- EXPORT ICON COMPONENTS --*/
export { default as Edit } from './icons/Edit';
export { default as CopyPassword } from './icons/CopyPassword';
export { default as Reveal } from './icons/Reveal';
export { default as Hide } from './icons/Hide';
export { default as NoNetwork } from './icons/NoNetwork';
export { default as Shared } from './icons/Shared';
export { default as Loader } from './icons/Loader';
export { default as CaretDown } from './icons/CaretDown';
export { default as Check } from './icons/Check';
export { default as Vault } from './icons/Vault';
export { default as Web } from './icons/Web';
export { default as Generator } from './icons/Generator';
export { default as Dots } from './icons/Dots';
export { default as Search } from './icons/Search';
export { default as Close } from './icons/Close';
export { default as ArrowDown } from './icons/ArrowDown';
export { default as Warning } from './icons/Warning';
export { default as Refresh } from './icons/Refresh';
export { default as Tools } from './icons/Tools';
export { default as Computer } from './icons/Computer';
export { default as LogOut } from './icons/LogOut';
export { default as PasswordChanger } from './icons/PasswordChanger';
export { default as SecurityDashboard } from './icons/SecurityDashboard';
export { default as PasswordHistory } from './icons/PasswordHistory';
export { default as Passwords } from './icons/Passwords';
